restart_file: .na
start_datetime: 2026-04-30 00:00:00
end_datetime: .na
forecast_start_datetime: 2026-05-04 00:00:00
forecast_horizon: 1
sim_name: glm_aed_flare_rs_demo_v3
configure_flare: configure_flare_glm_aed.yml
configure_obs: observation_processing.yml
use_s3: TRUE
use_faasr: TRUE
